In [1]:
a = True       #assign true value to vaiable a
b = False       #assign false value to vaiable b
print(type(a))   # print type of a 
print (a and a)   # and condition return true if both condition is true so its return true if a is true
print (a and b)   # return true if both a and b is true
print (b and a)   #return true if both and b is true
print (b and a)  #return true if both a and b is true
print ( a or b)   #or condition return true if any condition is true and return false if both conditions are false
print (not a)     #reverse the result of condition
print (a != b)    #return true if value on left is not equal to right

<class 'bool'>
True
False
False
False
True
False
True


In [8]:
a = "True"     # string type of a and b
b = "False"
print(type(a))
print (a and a)
print (a and b)
print (b and a)
print (b and a)
print ( a or b)
print (not a)
print (a != b)

<class 'str'>
True
False
True
True
True
False
True


In [35]:
t = 1      # type of variable t,f,g is integer 1 represent ture and 0 represent false
f = 0
g = 1
print(type(t))
c = t and f and g    # assign truth value of  t and f and g to c
print(c)
m = t or g or f
print(m)
v = t and f or g
print(v)
u = t or f and g
print(u)
l=t!=g             # assign truth value of  t!= g to l
print(l)
k=t!=f
print(k)
print(not c)

<class 'int'>
0
1
1
1
False
True
True


In [41]:
nums = list(range(5)) # defining array of 5 elements (0 to 4)
print(nums)
print(nums [2:4])     # slicing array from 2 to 4
print(nums[2:])       #  elemet of array after 2
print(nums[:2])        #  elemet of array before 2
print(nums[:])        # all element of array 
print(nums[:-1])    # length of array decrease by 1 from last
nums[1:2] = [8,9]    # adjust 8,9 between 1:2   or defining new array from previous
print(nums)
nums[2:4] = [8,9,10]   
print(nums)


[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 8, 9, 2, 3, 4]
[0, 8, 8, 9, 10, 3, 4]


In [34]:
import numpy as np
nums=np.linspace(0,5,10)
print(nums)
print(nums[0:])
print(nums[:0])
print(nums[:4])
print(nums[:])
print(nums[:-4])

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[]
[0.         0.55555556 1.11111111 1.66666667]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778]


In [43]:
nums= np.arange(0,5,2)
print(nums)
print(nums[0:])
print(nums[:0])
print(nums[:4])
print(nums[:])
print(nums[:-4])
print(nums[:-1])
print(nums[1:2])
nums[1:3]=[3,4]
print(nums)
nums[1:3]=[3,4,5]

[0 2 4]
[0 2 4]
[]
[0 2 4]
[0 2 4]
[]
[0 2]
[2]
[0 3 4]


ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
a=5       #intialization variable
b=5
if a==b :      # condition
    print("my name is iqra arshad")     # body of if statement 

my name is iqra arshad


In [2]:
a=4
if a==4:          # if condtion
    for i in range(a):       # for loop in the body of if statement ; range(a) (a iteration = 0 t0 a-1 )
        print(i)             # body of for loop

0
1
2
3


In [3]:
x=5
f= lambda x: 2*x**2+2       # in order to define the function we need to used keyword lambda 
f(x)
x1 =float(input('enter x1:'))    # taking numbers from user whose data type is floating 
x2 =float(input('enter x2:'))
print(f(x1))
print(f(x2))

enter x1:5
enter x2:0
52.0
2.0
