# numpy arrays

import numpy as np

In [3]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [6]:
np.ones(101)     # built in function to define array of some array with same number 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.arange(6)     # a sequence start from zero and with six value exclsuive last one

array([0, 1, 2, 3, 4, 5])

In [11]:
np.arange(3,6)     # start and end value excluding last one

array([3, 4, 5])

In [12]:
np.arange(4,12,3)    # start and end value and 3 is step

array([ 4,  7, 10])

In [16]:
np.arange(4,12,5)

array([4, 9])

In [13]:
np.linspace(6,12,3)    # array starting and ending value(exclusive) and with 3 element

array([ 6.,  9., 12.])

In [15]:
np.linspace(6,12,1)

array([6.])

In [14]:
np.linspace(6,12)    # if we dont give number of element in linspace 

array([ 6.        ,  6.12244898,  6.24489796,  6.36734694,  6.48979592,
        6.6122449 ,  6.73469388,  6.85714286,  6.97959184,  7.10204082,
        7.2244898 ,  7.34693878,  7.46938776,  7.59183673,  7.71428571,
        7.83673469,  7.95918367,  8.08163265,  8.20408163,  8.32653061,
        8.44897959,  8.57142857,  8.69387755,  8.81632653,  8.93877551,
        9.06122449,  9.18367347,  9.30612245,  9.42857143,  9.55102041,
        9.67346939,  9.79591837,  9.91836735, 10.04081633, 10.16326531,
       10.28571429, 10.40816327, 10.53061224, 10.65306122, 10.7755102 ,
       10.89795918, 11.02040816, 11.14285714, 11.26530612, 11.3877551 ,
       11.51020408, 11.63265306, 11.75510204, 11.87755102, 12.        ])

In [18]:
len(np.linspace(6,12)) 

50

# array operation

In [19]:
x=np.linspace(-10,5,10)
print(x)

[-10.          -8.33333333  -6.66666667  -5.          -3.33333333
  -1.66666667   0.           1.66666667   3.33333333   5.        ]


In [21]:
y=x**2
print(y)

[100.          69.44444444  44.44444444  25.          11.11111111
   2.77777778   0.           2.77777778  11.11111111  25.        ]


In [22]:
x=np.sqrt(y)
print(x)

[10.          8.33333333  6.66666667  5.          3.33333333  1.66666667
  0.          1.66666667  3.33333333  5.        ]


In [24]:
v=x+y     # adding array element wise
print(v)

[110.          77.77777778  51.11111111  30.          14.44444444
   4.44444444   0.           4.44444444  14.44444444  30.        ]


In [25]:
w=x*y
print(w)

[1000.          578.7037037   296.2962963   125.           37.03703704
    4.62962963    0.            4.62962963   37.03703704  125.        ]


In [26]:
z=x/y
print(z)

[0.1  0.12 0.15 0.2  0.3  0.6   nan 0.6  0.3  0.2 ]


C:\Users\Dee\AppData\Local\Temp/ipykernel_10620/3202974670.py:1: RuntimeWarning: invalid value encountered in true_divide
  z=x/y
